const images = [
    { alt: '', src: '/images/bigSomething.jpg' },
    { alt: '', src: '/images/bigSomethingOne.jpg' },
    { alt: '', src: '/images/bigSomethingTwo.jpg' },
    { alt: '', src: '/images/confetti.jpg' },
    { alt: '', src: '/images/confettiTwo.jpg' },
    { alt: '', src: '/images/crowd.jpg' },
    { alt: '', src: '/images/crowdTwo.jpg' },
    { alt: '', src: '/images/cryoGuitarJumping.jpg' },
    { alt: '', src: '/images/d1.jpg' },
    { alt: '', src: '/images/dorfexBox.jpg' },
    { alt: '', src: '/images/dreadlocks.jpg' },
    { alt: '', src: '/images/f2.jpg' },
    { alt: '', src: '/images/firmament.jpg' },
    { alt: '', src: '/images/funkYou.jpg' },
    { alt: '', src: '/images/greenLazers.jpg' },
    { alt: '', src: '/images/lazers.jpg' },
    { alt: '', src: '/images/lazerwolf.jpg' },
    { alt: '', src: '/images/lazerwulfFour.jpg' },
    { alt: '', src: '/images/lazerwulfThree.jpg' },
    { alt: '', src: '/images/lazerwulfTwo.jpg' },
    { alt: '', src: '/images/lincolnTheaterOne.jpg' },
    { alt: '', src: '/images/moontype.jpg' },
    { alt: '', src: '/images/n1.jpg' },
    { alt: '', src: '/images/nghtmre.jpg' },
    { alt: '', src: '/images/pointingGirl.jpg' },
    { alt: '', src: '/images/pressPhotoOne.jpg' },
    { alt: '', src: '/images/pressPhotoTwo.jpg' },
    { alt: '', src: '/images/pressPhotoThree.jpg' },
    { alt: '', src: '/images/proposal.jpg' },
    { alt: '', src: '/images/redLazers.jpg' },
    { alt: '', src: '/images/reyka.jpg' },
    { alt: '', src: '/images/reykaTwo.jpg' },
    { alt: '', src: '/images/rye.jpg' },
    { alt: '', src: '/images/ryeTwo.jpg' },
    { alt: '', src: '/images/sanHoloGuitarCenter.jpg' },
    { alt: '', src: '/images/sanHoloGuitarCrowdBowing.jpg' },
    { alt: '', src: '/images/templeDenver.jpg' },
    { alt: '', src: '/images/warez1.jpg' },
    { alt: '', src: '/images/warez2.jpg' },
    { alt: '', src: '/images/warez6.jpg' },
    { alt: '', src: '/images/x3.jpg' }
];

export default images;