backend:
  name: git-gateway
  branch: master
logo_url: https://i.imgur.com/nLKzxBE.png
media_library:
  name: cloudinary
  config:
    cloud_name: ${file(.env):${process.env.CLOUDINARY_CLOUD_NAME}}
    api_key: ${file(.env):${process.env.CLOUDINARY_API_KEY}}